### PR TITLE
Serde validation latest

### PR DESCRIPTION
**Pull request by radovanradic**
Updating to latest serde M6 and validation M7 is throwing unexpected validation error (Bad Request).

### CODE REVIEW

**Comment by radovanradic** [comment]
This call
```
// testCRUD()
owner = ownersClient.save(new OwnerDto(null, "Joe", 25));
```
 is failing now with latest serde and validation with the error

> Task :micronaut-test-graalvm:micronaut-mssql:test
example.controllers.SqlServerApp
  JUnit Jupiter
    TestApp
      Test crud() FAILED
      io.micronaut.http.client.exceptions.HttpClientResponseException: Bad Request
          at app//io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.makeErrorFromRequestBody(DefaultHttpClient.java:2267)

any idea what has changed @yawkat, @dstepanov or if we are missing something now? Seems like body is empty or something like that.

**Comment by yawkat** [comment]
my guess is null handling

**Comment by radovanradic** [comment]
> is there a way to run this test in IDE? it just says `Unable to create a ConnectionFactory for 'ConnectionFactoryOptions{options={}}'. Available drivers: [ sqlserver ]` when I try

You can try any test in test-graalvm module, h2 easiest and fastest to reproduce

**Comment by radovanradic** [comment]
> it was just missing `@Body`, i pushed the fix

Great, thanks @yawkat !

**Pull request merged**
